# Generated by Django 5.0.3 on 2024-04-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer_contact',
        ),
    ]
